export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const REFRESH_TOKEN_ADMIN_START = "REFRESH_TOKEN_ADMIN_START";
export const REFRESH_TOKEN_ADMIN_SUCCESS = "REFRESH_TOKEN_ADMIN_SUCCESS";
export const REFRESH_TOKEN_ADMIN_FAIL = "REFRESH_TOKEN_ADMIN_FAIL";

export const ACCEPT_TOKEN_GET_ADMIN_START = "ACCEPT_TOKEN_GET_ADMIN_START";
export const ACCEPT_TOKEN_GET_ADMIN_SUCCESS = "ACCEPT_TOKEN_GET_ADMIN_SUCCESS";
export const ACCEPT_TOKEN_GET_ADMIN_FAIL = "ACCEPT_TOKEN_GET_ADMIN_FAIL";

export const CHANGE_ADMIN_PASSWORD_START = "CHANGE_ADMIN_PASSWORD_START";
export const CHANGE_ADMIN_PASSWORD_SUCCESS = "CHANGE_ADMIN_PASSWORD_SUCCESS";
export const CHANGE_ADMIN_PASSWORD_FAIL = "CHANGE_ADMIN_PASSWORD_FAIL";

export const GET_ALL_USER_START = "GET_ALL_USER_START";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_ALL_PRODUCT_START = "GET_ALL_PRODUCT_START";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const UPLOAD_ALL_USER_ADMIN_START = "UPLOAD_ALL_USER_ADMIN_START";
export const UPLOAD_ALL_USER_ADMIN_SUCCESS = "UPLOAD_ALL_USER_ADMIN_SUCCESS";
export const UPLOAD_ALL_USER_ADMIN_FAIL = "UPLOAD_ALL_USER_ADMIN_FAIL";

export const DELETE_ALL_USER_ADMIN_START = "DELETE_ALL_USER_ADMIN_START";
export const DELETE_ALL_USER_ADMIN_SUCCESS = "DELETE_ALL_USER_ADMIN_SUCCESS";
export const DELETE_ALL_USER_ADMIN_FAIL = "DELETE_ALL_USER_ADMIN_FAIL";
