export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const REFRESH_TOKEN_ADMIN_START = "REFRESH_TOKEN_ADMIN_START";
export const REFRESH_TOKEN_ADMIN_SUCCESS = "REFRESH_TOKEN_ADMIN_SUCCESS";
export const REFRESH_TOKEN_ADMIN_FAIL = "REFRESH_TOKEN_ADMIN_FAIL";
