import { FaLanguage, FaPizzaSlice, FaShoppingCart } from "react-icons/fa";
import {
  MdOutlineNotificationsNone,
  MdArrowDownward,
  MdLineStyle,
  MdTimeline,
  MdPermIdentity,
  MdStorefront,
  MdAttachMoney,
  MdMailOutline,
  MdDynamicFeed,
  MdChatBubbleOutline,
  MdWorkOutline,
  MdReportProblem,
} from "react-icons/md";
import { FiSettings, FiTrendingUp } from "react-icons/fi";
import { AiOutlineBarChart } from "react-icons/ai";
import { IoMdAnalytics } from "react-icons/io";
export {
  FaLanguage,
  MdOutlineNotificationsNone,
  FiSettings,
  FaPizzaSlice,
  FaShoppingCart,
  MdArrowDownward,
  MdLineStyle,
  MdTimeline,
  FiTrendingUp,
  MdPermIdentity,
  MdStorefront,
  MdAttachMoney,
  AiOutlineBarChart,
  MdMailOutline,
  MdDynamicFeed,
  MdChatBubbleOutline,
  MdWorkOutline,
  MdReportProblem,
  IoMdAnalytics,
};
// Timeline,
// TrendingUp,
// PermIdentity,
// Storefront,
// AttachMoney,
// BarChart,
// MailOutline,
// DynamicFeed,
// ChatBubbleOutline,
// WorkOutline,
// Report,
