import content from "../images/home-img.png";
import content2 from "../images/pizza2.png";
import content5 from "../images/pizza-5.png";
import content3 from "../images/pizza3.png";
import content4 from "../images/pizza4.png";
import img from "../images/s-img-1.jpg";
import img1 from "../images/s-img-2.jpg";
import img2 from "../images/s-img-3.jpg";
import img3 from "../images/s-img-4.jpg";
import img4 from "../images/s-img-5.jpg";
import img5 from "../images/s-img-6.jpg";
export { content, content2, content3, content4, content5 };
