export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const FORGET_ADMIN_START = "FORGET_ADMIN_START";
export const FORGET_ADMIN_SUCCESS = "FORGET_ADMIN_SUCCESS";
export const FORGET_ADMIN_FAIL = "FORGET_ADMIN_FAIL";

export const REFRESH_TOKEN_ADMIN_START = "REFRESH_TOKEN_ADMIN_START";
export const REFRESH_TOKEN_ADMIN_SUCCESS = "REFRESH_TOKEN_ADMIN_SUCCESS";
export const REFRESH_TOKEN_ADMIN_FAIL = "REFRESH_TOKEN_ADMIN_FAIL";

export const ACCEPT_TOKEN_GET_ADMIN_START = "ACCEPT_TOKEN_GET_ADMIN_START";
export const ACCEPT_TOKEN_GET_ADMIN_SUCCESS = "ACCEPT_TOKEN_GET_ADMIN_SUCCESS";
export const ACCEPT_TOKEN_GET_ADMIN_FAIL = "ACCEPT_TOKEN_GET_ADMIN_FAIL";

export const CHANGE_ADMIN_PASSWORD_START = "CHANGE_ADMIN_PASSWORD_START";
export const CHANGE_ADMIN_PASSWORD_SUCCESS = "CHANGE_ADMIN_PASSWORD_SUCCESS";
export const CHANGE_ADMIN_PASSWORD_FAIL = "CHANGE_ADMIN_PASSWORD_FAIL";

export const GET_ALL_USER_START = "GET_ALL_USER_START";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_ALL_ADMIN_START = "GET_ALL_ADMIN_START";
export const GET_ALL_ADMIN_SUCCESS = "GET_ALL_ADMIN_SUCCESS";
export const GET_ALL_ADMIN_FAIL = "GET_ALL_ADMIN_FAIL";

export const GET_ALL_PRODUCT_START = "GET_ALL_PRODUCT_START";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const UPLOAD_ALL_USER_ADMIN_START = "UPLOAD_ALL_USER_ADMIN_START";
export const UPLOAD_ALL_USER_ADMIN_SUCCESS = "UPLOAD_ALL_USER_ADMIN_SUCCESS";
export const UPLOAD_ALL_USER_ADMIN_FAIL = "UPLOAD_ALL_USER_ADMIN_FAIL";

export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_START";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

export const GET_ALL_PAYMENT_START = "GET_ALL_PAYMENT_START";
export const GET_ALL_PAYMENT_SUCCESS = "GET_ALL_PAYMENT_SUCCESS";
export const GET_ALL_PAYMENT_FAIL = "GET_ALL_PAYMENT_FAIL";

export const GET_ALL_BILL_START = "GET_ALL_BILL_START";
export const GET_ALL_BILL_SUCCESS = "GET_ALL_BILL_SUCCESS";
export const GET_ALL_BILL_FAIL = "GET_ALL_BILL_FAIL";

export const GET_ALL_RATING_START = "GET_ALL_RATING_START";
export const GET_ALL_RATING_SUCCESS = "GET_ALL_RATING_SUCCESS";
export const GET_ALL_RATING_FAIL = "GET_ALL_RATING_FAIL";

export const GET_ALL_APP_INFO_START = "GET_ALL_APP_INFO_START";
export const GET_ALL_APP_INFO_SUCCESS = "GET_ALL_APP_INFO_SUCCESS";
export const GET_ALL_APP_INFO_FAIL = "GET_ALL_APP_INFO_FAIL";

export const GET_ALL_BILL_DETAIL_START = "GET_ALL_BILL_DETAIL_START";
export const GET_ALL_BILL_DETAIL_SUCCESS = "GET_ALL_BILL_DETAIL_SUCCESS";
export const GET_ALL_BILL_DETAIL_FAIL = "GET_ALL_BILL_DETAIL_FAIL";

export const GET_ACCOUNT_NEW_START = "GET_ACCOUNT_NEW_START";
export const GET_ACCOUNT_NEW_SUCCESS = "GET_ACCOUNT_NEW_SUCCESS";
export const GET_ACCOUNT_NEW_FAIL = "GET_ACCOUNT_NEW_FAIL";

export const GET_ACCOUNT_BUY_MUCH_START = "GET_ACCOUNT_BUY_MUCH_START";
export const GET_ACCOUNT_BUY_MUCH_SUCCESS = "GET_ACCOUNT_BUY_MUCH_SUCCESS";
export const GET_ACCOUNT_BUY_MUCH_FAIL = "GET_ACCOUNT_BUY_MUCH_FAIL";

export const PRODUCT_TOTAL_START = "PRODUCT_TOTAL_START";
export const PRODUCT_TOTAL_SUCCESS = "PRODUCT_TOTAL_SUCCESS";
export const PRODUCT_TOTAL_FAIL = "PRODUCT_TOTAL_FAIL";

export const PRODUCT_TOTAL_CANCEL_START = "PRODUCT_TOTAL_CANCEL_START";
export const PRODUCT_TOTAL_CANCEL_SUCCESS = "PRODUCT_TOTAL_CANCEL_SUCCESS";
export const PRODUCT_TOTAL_CANCEL_FAIL = "PRODUCT_TOTAL_CANCEL_FAIL";

export const PRODUCT_TOTAL_NOT_RECEIVED_START =
  "PRODUCT_TOTAL_NOT_RECEIVED_START";
export const PRODUCT_TOTAL_NOT_RECEIVED_SUCCESS =
  "PRODUCT_TOTAL_NOT_RECEIVED_SUCCESS";
export const PRODUCT_TOTAL_NOT_RECEIVED_FAIL =
  "PRODUCT_TOTAL_NOT_RECEIVED_FAIL";

export const PRODUCT_TOTAL_MOTH_START = "PRODUCT_TOTAL_MOTH_START";
export const PRODUCT_TOTAL_MOTH_SUCCESS = "PRODUCT_TOTAL_MOTH_SUCCESS";
export const PRODUCT_TOTAL_MOTH_FAIL = "PRODUCT_TOTAL_MOTH_FAIL";

export const VOUCHER_ALL_START = "VOUCHER_ALL_START";
export const VOUCHER_ALL_SUCCESS = "VOUCHER_ALL_SUCCESS";
export const VOUCHER_ALL_FAIL = "VOUCHER_ALL_FAIL";

export const COMPARE_REVENUE_TOTAL_BUY_MOTH_START =
  "COMPARE_REVENUE_TOTAL_BUY_MOTH_STAR";
export const COMPARE_REVENUE_TOTAL_BUY_MOTH_SUCCESS =
  "COMPARE_REVENUE_TOTAL_BUY_MOTH_SUCCESS";
export const COMPARE_REVENUE_TOTAL_BUY_MOTH_FAIL =
  "COMPARE_REVENUE_TOTAL_BUY_MOTH_FAIL";

export const COMPARE_REVENUE_TOTAL_CANCEL_MOTH_START =
  "COMPARE_REVENUE_TOTAL_CANCEL_MOTH_STAR";
export const COMPARE_REVENUE_TOTAL_CANCEL_MOTH_SUCCESS =
  "COMPARE_REVENUE_TOTAL_CANCEL_MOTH_SUCCESS";
export const COMPARE_REVENUE_TOTAL_CANCEL_MOTH_FAIL =
  "COMPARE_REVENUE_TOTAL_CANCEL_MOTH_FAIL";

export const COMPARE_REVENUE_TOTAL_NOT_RECEIVED_MOTH_START =
  "COMPARE_REVENUE_TOTAL_NOT_RECEIVED_MOTH_STAR";
export const COMPARE_REVENUE_TOTAL_NOT_RECEIVED_MOTH_SUCCESS =
  "COMPARE_REVENUE_TOTAL_NOT_RECEIVED_MOTH_SUCCESS";
export const COMPARE_REVENUE_TOTAL_NOT_RECEIVED_MOTH_FAIL =
  "COMPARE_REVENUE_TOTAL_NOT_RECEIVED_MOTH_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";
